### ISSUE TITLE
执行 npm run dll 报错

### ISSUE THREAD

**Issue by zollero** [llh520xw/React#2]
报错需要 jquery 模块。
![image](https://cloud.githubusercontent.com/assets/8801894/19218556/adb352c4-8e2f-11e6-8c82-6bc3123c16e8.png)

**Comment by leilihuang** [comment]
可以在webpack.dll.config.js配置文件中，将jquery删除掉

**Comment by PandaWizard** [comment]
npm ERR! Failed at the leilihuang@1.0.0 dll script 'webpack --config webpack.dll.js'.
npm ERR! This is most likely a problem with the leilihuang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.dll.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls leilihuang
npm ERR! There is likely additional logging output above.

运行npm run dll会报如上错误
